CREATE TABLE users (
    int_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    full_name TEXT NOT NULL, 
    email VARCHAR(320) NOT NULL, 
    phone VARCHAR(15) NOT NULL, 
    joined CURRENT_TIMESTAMP() NOT NULL, 
    deactivated DATE DEFAULT NULL
);
