CREATE TABLE sublets (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    public_id uuid DEFAULT uuid_generate_v4(),
    owner INTEGER REFERENCES users(id) NOT NULL,
    title TEXT NOT NULL, 
    address VARCHAR(250) NOT NULL, 
    geocode VARCHAR(100),
    description TEXT, 
    num_rooms INTEGER NOT NULL, 
    num_sleeps INTEGER NOT NULL, 
    start_date DATE NOT NULL DEFAULT now(),
    end_date  DATE NOT NULL,
    posted_date TIMESTAMP NOT NULL DEFAULT now(), 
    lon float(8), 
    lat float(8),
    geo_marker GEOGRAPHY
);