CREATE TABLE sublets (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    owner INTEGER REFERENCES users(id) NOT NULL,
    title TEXT NOT NULL, 
    address VARCHAR(250) NOT NULL, 
    description TEXT, 
    num_rooms INTEGER NOT NULL, 
    num_sleeps INTEGER NOT NULL, 
    start_date DATE NOT NULL DEFAULT now(),
    end_date  DATE NOT NULL,
    posted_date TIMESTAMP
);