CREATE TABLE comms (
    int_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id uuid DEFAULT uuid_generate_v4(),
    property_id INTEGER REFERENCES sublets(id) NOT NULL, 
    sender VARCHAR(320) NOT NULL, 
    recipient INTEGER REFERENCES users(id) NOT NULL, 
    message TEXT NOT NULL
);